cvp_instance_ips:
  - apiserver.arista.io

# local users
local_users:
  - name: cvpadmin
    privilege: 15
    role: network-admin
    sha512_password: $6$ikGzKyb6w4yEqLly$mJLofKfPrT2Mx6UffrY2dwFXuTCbtf2Okjfu9CgyuduVdN3WIrq9quRZXXFjrRI754ewFQ3uZSlwSEKAe2zbP1

# vEOS
p2p_uplinks_mtu: 1500

# Max spines
max_spines: 2

# DNS Servers
ip_name_servers:
  - ip_address: 169.254.169.254
    vrf: default
  - ip_address: 8.8.8.8
    vrf: default
  - ip_address: 1.1.1.1
    vrf: default

# NTP servers
ntp:
  servers:
    - name: pool.ntp.org
      vrf: default

# ACT agent
agents:
  - name: KernelFib
    environment_variables:
      - name: KERNELFIB_PROGRAM_ALL_ECMP
        value: "'true'"

custom_structured_configuration_management_interfaces:
  - name: Management1
    lldp:
      transmit: false
      receive: false

l3_edge:
  p2p_links:
    # DCI Link - BL01-8340 (Kingston) to SS01-8595 (Lefrak)
    - nodes: [OTI-DC01-Leaf5A,  OTI-DC02-Leaf5A]
      interfaces: [Ethernet52/1, Ethernet52/1]
      ip: [192.168.10.249/31, 192.168.10.248/31]
      as: [65005, 65105]
      include_in_underlay_protocol: true
    # DCI Link - BL02-8340 (Kingston) to SS02-8595 (Grahamsville)
    - nodes: [OTI-DC01-Leaf5B, OTI-DC02-Leaf5B]
      interfaces: [Ethernet52/1, Ethernet52/1]
      ip: [192.168.10.250/31, 192.168.10.251/31]
      as: [65005, 65105]
      include_in_underlay_protocol: true

# AVD Settings
# Dump all vars and facts per device after generating `avd_switch_facts`.
avd_eos_designs_debug: false

# Generate structured configuration per device.
avd_eos_designs_structured_config: true

# Unset `avd_switch_facts` to gain a small performance improvement since Ansible needs to handle fewer variables.
avd_eos_designs_unset_facts: true
# Include connected endpoints in the fabric-wide documentation.
eos_designs_documentation:
  connected_endpoints: true

# EOS connection vars
ansible_connection: httpapi
ansible_network_os: eos
ansible_user: cvpadmin
# should use vault for passwords
ansible_ssh_pass: arista123
ansible_become: true
ansible_become_method: enable
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false