---
tenants:
  - name: OTI
    mac_vrf_vni_base: 10000
    vrfs:
      - name: Production
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 10
          loopback_ip_pools:
            - pod: DC01_Pod1
              ipv4_pool: 10.1.10.0/27
            - pod: DC02_Pod1
              ipv4_pool: 10.2.10.0/27
        svis:
          - id: 100
            name: Compute
            enabled: true
            ip_address_virtual: 10.10.100.1/24
            tags:
              - compute
          - id: 101
            name: Data
            enabled: true
            ip_address_virtual: 10.10.101.1/24
            tags:
              - data
              - border
          - id: 3434
            name: Server_MGMT
            enabled: true
            ip_address_virtual: 10.34.34.1/24
            tags:
              - vms
          - id: 3545
            name: Server_MGMT
            enabled: true
            ip_address_virtual: 10.35.45.1/24
            tags:
              - idrac_dc01
      - name: Development
        vrf_vni: 11
        vtep_diagnostic:
          loopback: 11
          loopback_ip_pools:
            - pod: DC01_Pod1
              ipv4_pool: 10.1.11.0/27
            - pod: DC02_Pod1
              ipv4_pool: 10.2.11.0/27
        svis:
          - id: 21
            name: VRF11_VLAN21
            enabled: true
            ip_address_virtual: 10.10.21.1/24
          - id: 22
            name: VRF11_VLAN22
            enabled: true
            ip_address_virtual: 10.10.22.1/24

    l2vlans:
      - id: 3401
        name: L2_VLAN3401
      - id: 3402
        name: L2_VLAN3402