servers:
-  name: DC01-0601-ESX01
   rack: 0601.01.Rack01
   adapters:
   -  endpoint_ports:
      - idrac
      switch_ports:
      - Ethernet1
      switches:
      - OTI-DC01-OBM1
      mode: access
      vlans: '3545'
      profile: Access
   -  endpoint_ports:
      - Onboard_NIC_1
      - PCI_slot_1_Port_1
      switch_ports:
      - Ethernet1
      - Ethernet1
      switches:
      - OTI-DC01-Leaf1
      - OTI-DC01-Leaf2
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      ethernet_segment:
         short_esi: auto
      profile: Access
   -  endpoint_ports:
      - Onboard_NIC_2
      - PCI_slot_2_Port_2
      switch_ports:
      - Ethernet25
      - Ethernet25
      switches:
      - OTI-DC01-Leaf1
      - OTI-DC01-Leaf2
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      ethernet_segment:
         short_esi: auto
      profile: Access
   -  endpoint_ports:
      - PCI_slot_1_Port_2
      - PCI_slot_2_Port_1
      switch_ports:
      - Ethernet1
      - Ethernet1
      switches:
      - OTI-DC01-Leaf5A
      - OTI-DC01-Leaf5B
      mode: trunk
      vlans: 2821, 2822, 2833, 2834
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
port_profiles:
-  profile: Access
   spanning_tree_portfast: edge
