port_profiles:
-  profile: Access
   spanning_tree_portfast: edge
servers:
-  adapters:
   -  endpoint_ports:
      - idrac
      mode: access
      profile: Access
      switch_ports:
      - Ethernet1
      switches:
      - OTI-DC01-OBM1
      vlans: '3545'
   -  endpoint_ports:
      - Onboard_NIC_1
      - PCI_slot_1_Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet1
      - Ethernet1
      switches:
      - OTI-DC01-Leaf1
      - OTI-DC01-Leaf2
   -  endpoint_ports:
      - Onboard_NIC_2
      - PCI_slot_2_Port_2
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet25
      - Ethernet25
      switches:
      - OTI-DC01-Leaf1
      - OTI-DC01-Leaf2
   -  endpoint_ports:
      - PCI_slot_1_Port_2
      - PCI_slot_2_Port_1
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet1
      - Ethernet1
      switches:
      - OTI-DC01-Leaf5A
      - OTI-DC01-Leaf5B
      vlans: 2821, 2822, 2833, 2834
   name: DC01-0601-ESX01
   rack: 0601.01.Rack01
-  adapters:
   -  endpoint_ports:
      - idrac
      mode: access
      profile: Access
      switch_ports:
      - Ethernet2
      switches:
      - OTI-DC01-OBM1
      vlans: '3545'
   -  endpoint_ports:
      - Onboard_NIC_1
      - PCI_slot_1_Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet2
      - Ethernet2
      switches:
      - OTI-DC01-Leaf1
      - OTI-DC01-Leaf2
   -  endpoint_ports:
      - Onboard_NIC_2
      - PCI_slot_2_Port_2
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet26
      - Ethernet26
      switches:
      - OTI-DC01-Leaf1
      - OTI-DC01-Leaf2
   -  endpoint_ports:
      - PCI_slot_1_Port_2
      - PCI_slot_2_Port_1
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet2
      - Ethernet2
      switches:
      - OTI-DC01-Leaf5A
      - OTI-DC01-Leaf5B
      vlans: '821'
   name: DC01-0601-ESX02
   rack: 0601.01.Rack01
-  adapters:
   -  endpoint_ports:
      - idrac
      mode: access
      profile: Access
      switch_ports:
      - Ethernet1
      switches:
      - OTI-DC02-OBM1
      vlans: '2545'
   -  endpoint_ports:
      - Onboard_NIC_1
      - PCI_slot_1_Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet1
      - Ethernet1
      switches:
      - OTI-DC02-Leaf1
      - OTI-DC02-Leaf2
   -  endpoint_ports:
      - Onboard_NIC_2
      - PCI_slot_2_Port_2
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet48
      - Ethernet48
      switches:
      - OTI-DC02-Leaf1
      - OTI-DC02-Leaf2
   -  endpoint_ports:
      - PCI_slot_1_Port_2
      - PCI_slot_2_Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet1
      - Ethernet1
      switches:
      - OTI-DC02-Leaf3
      - OTI-DC02-Leaf4
   name: DC02-0901-ESX01
   rack: 0901.01.Rack01
-  adapters:
   -  endpoint_ports:
      - idrac
      mode: access
      profile: Access
      switch_ports:
      - Ethernet2
      switches:
      - OTI-DC02-OBM1
      vlans: '2545'
   -  endpoint_ports:
      - Onboard_NIC_1
      - PCI_slot_1_Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet2
      - Ethernet2
      switches:
      - OTI-DC02-Leaf1
      - OTI-DC02-Leaf2
   -  endpoint_ports:
      - Onboard_NIC_2
      - PCI_slot_2_Port_2
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet47
      - Ethernet47
      switches:
      - OTI-DC02-Leaf1
      - OTI-DC02-Leaf2
   -  endpoint_ports:
      - PCI_slot_1_Port_2
      - PCI_slot_2_Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet2
      - Ethernet2
      switches:
      - OTI-DC02-Leaf3
      - OTI-DC02-Leaf4
   name: DC02-0901-ESX02
   rack: 0901.01.Rack01
-  adapters:
   -  endpoint_ports:
      - idrac
      mode: access
      profile: Access
      switch_ports:
      - Ethernet3
      switches:
      - OTI-DC01-OBM1
      vlans: '3545'
   -  endpoint_ports:
      - Onboard_NIC_1
      - PCI_slot_1_Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet11
      - Ethernet11
      switches:
      - OTI-DC01-Leaf1
      - OTI-DC01-Leaf2
   -  endpoint_ports:
      - Onboard_NIC_2
      - PCI_slot_2_Port_2
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet1
      - Ethernet1
      switches:
      - OTI-DC01-Leaf3
      - OTI-DC01-Leaf4
   -  endpoint_ports:
      - PCI_slot_1_Port_2
      - PCI_slot_2_Port_1
      mode: access
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet3
      - Ethernet3
      switches:
      - OTI-DC01-Leaf5A
      - OTI-DC01-Leaf5B
      vlans: '55'
   name: DC01-0601-ESX03
   rack: 0601.01.Rack02
-  adapters:
   -  endpoint_ports:
      - idrac
      mode: access
      profile: Access
      switch_ports:
      - Ethernet4
      switches:
      - OTI-DC01-OBM1
      vlans: '3545'
   -  endpoint_ports:
      - Onboard_NIC_1
      - PCI_slot_1_Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet12
      - Ethernet12
      switches:
      - OTI-DC01-Leaf1
      - OTI-DC01-Leaf2
   -  endpoint_ports:
      - Onboard_NIC_2
      - PCI_slot_2_Port_2
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet2
      - Ethernet2
      switches:
      - OTI-DC01-Leaf3
      - OTI-DC01-Leaf4
   -  endpoint_ports:
      - PCI_slot_1_Port_2
      - PCI_slot_2_Port_1
      mode: access
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet4
      - Ethernet4
      switches:
      - OTI-DC01-Leaf5A
      - OTI-DC01-Leaf5B
      vlans: '55'
   name: DC01-0601-ESX04
   rack: 0601.01.Rack02
-  adapters:
   -  endpoint_ports:
      - idrac
      mode: access
      profile: Access
      switch_ports:
      - Ethernet3
      switches:
      - OTI-DC02-OBM1
      vlans: '2545'
   -  endpoint_ports:
      - Onboard_NIC_1
      - PCI_slot_1_Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet3
      - Ethernet3
      switches:
      - OTI-DC02-Leaf1
      - OTI-DC02-Leaf2
   -  endpoint_ports:
      - Onboard_NIC_2
      - PCI_slot_2_Port_2
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet3
      - Ethernet3
      switches:
      - OTI-DC02-Leaf3
      - OTI-DC02-Leaf4
   -  endpoint_ports:
      - PCI_slot_1_Port_2
      - PCI_slot_2_Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet49/1
      - Ethernet49/1
      switches:
      - OTI-DC02-Leaf3
      - OTI-DC02-Leaf4
   name: DC02-0901-ESX03
   rack: 0901.01.Rack02
-  adapters:
   -  endpoint_ports:
      - idrac
      mode: access
      profile: Access
      switch_ports:
      - Ethernet4
      switches:
      - OTI-DC02-OBM1
      vlans: '2545'
   -  endpoint_ports:
      - Onboard_NIC_1
      - PCI_slot_1_Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet4
      - Ethernet4
      switches:
      - OTI-DC02-Leaf1
      - OTI-DC02-Leaf2
   -  endpoint_ports:
      - Onboard_NIC_2
      - PCI_slot_2_Port_2
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet1
      - Ethernet1
      switches:
      - OTI-DC02-Leaf5A
      - OTI-DC02-Leaf5B
      vlans: 899, 999
   -  endpoint_ports:
      - PCI_slot_1_Port_2
      - PCI_slot_2_Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet50/1
      - Ethernet50/1
      switches:
      - OTI-DC02-Leaf3
      - OTI-DC02-Leaf4
   name: DC02-0901-ESX04
   rack: 0901.01.Rack02
-  adapters:
   -  endpoint_ports:
      - iLo
      mode: access
      profile: Access
      switch_ports:
      - Ethernet7
      switches:
      - OTI-DC01-OBM1
      vlans: '3545'
   -  endpoint_ports:
      - Port_0
      - Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet11
      - Ethernet11
      switches:
      - OTI-DC01-Leaf3
      - OTI-DC01-Leaf4
   name: DC01-0601-SRVA
   rack: 0601.01.Rack13
-  adapters:
   -  endpoint_ports:
      - iLo
      mode: access
      profile: Access
      switch_ports:
      - Ethernet8
      switches:
      - OTI-DC01-OBM1
      vlans: '3545'
   -  endpoint_ports:
      - Port_0
      - Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet12
      - Ethernet12
      switches:
      - OTI-DC01-Leaf3
      - OTI-DC01-Leaf4
   name: DC01-0601-SRVB
   rack: 0601.01.Rack13
-  adapters:
   -  endpoint_ports:
      - iLo
      mode: access
      profile: Access
      switch_ports:
      - Ethernet9
      switches:
      - OTI-DC01-OBM1
      vlans: '3545'
   -  endpoint_ports:
      - Port_0
      - Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet13
      - Ethernet13
      switches:
      - OTI-DC01-Leaf3
      - OTI-DC01-Leaf4
   name: DC01-0601-SRVC
   rack: 0601.01.Rack13
-  adapters:
   -  endpoint_ports:
      - iLo
      mode: access
      profile: Access
      switch_ports:
      - Ethernet10
      switches:
      - OTI-DC01-OBM1
      vlans: '3545'
   -  endpoint_ports:
      - Port_0
      - Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet14
      - Ethernet14
      switches:
      - OTI-DC01-Leaf3
      - OTI-DC01-Leaf4
   -  endpoint_ports:
      - Port_2
      - Port_3
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet25
      - Ethernet25
      switches:
      - OTI-DC01-Leaf5A
      - OTI-DC01-Leaf5B
      vlans: 3911, 2500
   name: DC01-0601-SRVD
   rack: 0601.01.Rack13
-  adapters:
   -  endpoint_ports:
      - iLo
      mode: access
      profile: Access
      switch_ports:
      - Ethernet7
      switches:
      - OTI-DC02-OBM1
      vlans: '2545'
   -  endpoint_ports:
      - Port_0
      - Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet25
      - Ethernet25
      switches:
      - OTI-DC02-Leaf1
      - OTI-DC02-Leaf2
   -  endpoint_ports:
      - Port_2
      - Port_3
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet5
      - Ethernet5
      switches:
      - OTI-DC02-Leaf3
      - OTI-DC02-Leaf4
   name: DC02-0901-SRVA
   rack: 0901.01.Rack08
-  adapters:
   -  endpoint_ports:
      - iLo
      mode: access
      profile: Access
      switch_ports:
      - Ethernet8
      switches:
      - OTI-DC02-OBM1
      vlans: '2545'
   -  endpoint_ports:
      - Port_0
      - Port_1
      ethernet_segment:
         short_esi: auto
      mode: access
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet25
      - Ethernet25
      switches:
      - OTI-DC02-Leaf3
      - OTI-DC02-Leaf4
   name: DC02-0901-SRVB
   rack: 0901.01.Rack08
-  adapters:
   -  endpoint_ports:
      - iLo
      mode: access
      profile: Access
      switch_ports:
      - Ethernet9
      switches:
      - OTI-DC02-OBM1
      vlans: '2545'
   -  endpoint_ports:
      - Port_0
      - Port_1
      ethernet_segment:
         short_esi: auto
      mode: access
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet26
      - Ethernet26
      switches:
      - OTI-DC02-Leaf3
      - OTI-DC02-Leaf4
   name: DC02-0901-SRVC
   rack: 0901.01.Rack08
-  adapters:
   -  endpoint_ports:
      - idrac
      mode: access
      profile: Access
      switch_ports:
      - Ethernet5
      switches:
      - OTI-DC01-OBM1
      vlans: '3545'
   -  endpoint_ports:
      - Onboard_NIC_1
      - PCI_slot_1_Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet30
      - Ethernet30
      switches:
      - OTI-DC01-Leaf1
      - OTI-DC01-Leaf2
   -  endpoint_ports:
      - Onboard_NIC_2
      - PCI_slot_2_Port_2
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet3
      - Ethernet3
      switches:
      - OTI-DC01-Leaf3
      - OTI-DC01-Leaf4
   -  endpoint_ports:
      - PCI_slot_1_Port_2
      - PCI_slot_2_Port_1
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet5
      - Ethernet5
      switches:
      - OTI-DC01-Leaf5A
      - OTI-DC01-Leaf5B
      vlans: 2821, 2822, 2833, 2834
   name: DC01-0601-ESX05
   rack: 0601.01.Rack12
-  adapters:
   -  endpoint_ports:
      - idrac
      mode: access
      profile: Access
      switch_ports:
      - Ethernet6
      switches:
      - OTI-DC01-OBM1
      vlans: '3545'
   -  endpoint_ports:
      - Onboard_NIC_1
      - PCI_slot_1_Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet31
      - Ethernet31
      switches:
      - OTI-DC01-Leaf1
      - OTI-DC01-Leaf2
   -  endpoint_ports:
      - Onboard_NIC_2
      - PCI_slot_2_Port_2
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet4
      - Ethernet4
      switches:
      - OTI-DC01-Leaf3
      - OTI-DC01-Leaf4
   -  endpoint_ports:
      - PCI_slot_1_Port_2
      - PCI_slot_2_Port_1
      mode: access
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet6
      - Ethernet6
      switches:
      - OTI-DC01-Leaf5A
      - OTI-DC01-Leaf5B
      vlans: '821'
   name: DC01-0601-ESX06
   rack: 0601.01.Rack12
-  adapters:
   -  endpoint_ports:
      - idrac
      mode: access
      profile: Access
      switch_ports:
      - Ethernet5
      switches:
      - OTI-DC02-OBM1
      vlans: '2545'
   -  endpoint_ports:
      - Onboard_NIC_1
      - PCI_slot_1_Port_1
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet5
      - Ethernet5
      switches:
      - OTI-DC02-Leaf1
      - OTI-DC02-Leaf2
   -  endpoint_ports:
      - Onboard_NIC_2
      - PCI_slot_2_Port_2
      ethernet_segment:
         short_esi: auto
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet4
      - Ethernet4
      switches:
      - OTI-DC02-Leaf3
      - OTI-DC02-Leaf4
   -  endpoint_ports:
      - PCI_slot_1_Port_2
      - PCI_slot_2_Port_1
      mode: trunk
      mtu: 9214
      port_channel:
         mode: active
      profile: Access
      switch_ports:
      - Ethernet49/1
      - Ethernet49/1
      switches:
      - OTI-DC02-Leaf5A
      - OTI-DC02-Leaf5B
      vlans: 1100, 1101, 1102
   name: DC02-0901-ESX05
   rack: 0901.01.Rack09
