---
tenants:
  - name: OTI
    mac_vrf_vni_base: 10000
    vrfs:
      - name: BLUE
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 10
          loopback_ip_range: 10.255.10.0/27
        svis:
          - id: 11
            name: Compute
            enabled: true
            ip_address_virtual: 10.10.11.1/24
            tags:
              - compute
          - id: 12
            name: Data
            enabled: true
            ip_address_virtual: 10.10.12.1/24
            tags:
              - data
              - border
          - id: 13
            name: Server_MGMT
            enabled: true
            ip_address_virtual: 10.10.13.1/24
            tags:
              - idrac
      - name: RED
        vrf_vni: 11
        vtep_diagnostic:
          loopback: 11
          loopback_ip_range: 10.255.11.0/27
        svis:
          - id: 21
            name: VRF11_VLAN21
            enabled: true
            ip_address_virtual: 10.10.21.1/24
          - id: 22
            name: VRF11_VLAN22
            enabled: true
            ip_address_virtual: 10.10.22.1/24

    l2vlans:
      - id: 3401
        name: L2_VLAN3401
      - id: 3402
        name: L2_VLAN3402