---
- name: Translate excel to AVD Endpoints Data Models
  hosts: localhost
  connection: local
  tasks:
    - name: Test output
      shell: 'pwd'
      register: command_output
      run_once: True   
    - name: Run python script
      shell:
        cmd: "sudo python ./OTI_XLSX_TO_AVD_ENDPOINTS.py"
        chdir: "{{command_output.stdout}}/../"
      run_once: True        

- name: Build DC01 structured configuration
  hosts: DC01_Fabric
  connection: local
  gather_facts: no
  tasks:
    - name: generate intented variables
      import_role:
        name: arista.avd.eos_designs
      vars:
        documentation_dir_name: documentation/DC01

- name: Build DC01 OOB structured configuration
  hosts: DC01_OOB
  connection: local
  gather_facts: no
  tasks:
    - name: generate intented variables
      import_role:
        name: arista.avd.eos_designs
      vars:
        documentation_dir_name: documentation/DC01_OOB

- name: Build DC02 structured configuration
  hosts: DC02_Fabric
  connection: local
  gather_facts: no
  tasks:
    - name: generate intented variables
      import_role:
        name: arista.avd.eos_designs
      vars:
        documentation_dir_name: documentation/DC02

- name: Build DC02 OOB structured configuration
  hosts: DC02_OOB
  connection: local
  gather_facts: no
  tasks:
    - name: generate intented variables
      import_role:
        name: arista.avd.eos_designs
      vars:
        documentation_dir_name: documentation/DC02_OOB

- name: Generate CLI
  hosts: OTI
  connection: local
  gather_facts: no
  tasks:
    - name: generate device intended config and documentation
      import_role:
        name: arista.avd.eos_cli_config_gen
