- name: validate states on DC01 EOS devices
  hosts: DC01
  tasks:
    - name: validate states on EOS devices
      import_role:
         name: arista.avd.eos_validate_state
      vars:
        use_anta: true
        eos_validate_state_dir: '{{ root_dir }}/{{ eos_validate_state_name }}/{{ dc_name }}'
        eos_validate_state_md_report_path: '{{ eos_validate_state_dir }}/{{ dc_name }}-state.md'
        eos_validate_state_csv_report_path: '{{ eos_validate_state_dir }}/{{ dc_name }}-state.md'
- name: validate states on DC02 EOS devices
  hosts: DC02
  tasks:
    - name: validate states on EOS devices
      import_role:
         name: arista.avd.eos_validate_state
      vars:
        use_anta: true
        eos_validate_state_dir: '{{ root_dir }}/{{ eos_validate_state_name }}/{{ dc_name }}'
        eos_validate_state_md_report_path: '{{ eos_validate_state_dir }}/{{ dc_name }}-state.md'
        eos_validate_state_csv_report_path: '{{ eos_validate_state_dir }}/{{ dc_name }}-state.md'