name: Test the upcoming changes

on:
  push:
    branches-ignore:
      - main

jobs:
  dev:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install Python requirements
        run: pip install -r requirements-python.yml

      - name: Update OTI Endpoints based on xlsx
        run: python OTI_XLSX_TO_AVD_ENDPOINTS.py

      - name: Run pre-commit on files
        uses: pre-commit/action@v3.0.0

      - name: Check paths for group_vars/DC01
        uses: dorny/paths-filter@v3
        id: filter-site1
        with:
          filters: |
            workflows:
              - 'group_vars/DC01**'
              - 'group_vars/OTI_**'

      - name: Check paths for group_vars/DC02
        uses: dorny/paths-filter@v3
        id: filter-site2
        with:
          filters: |
            workflows:
              - 'group_vars/DC02**'
              - 'group_vars/OTI_**'

      - name: Install collections
        run: ansible-galaxy collection install -r requirements.yml
        if: steps.filter-site1.outputs.workflows == 'true' || steps.filter-site2.outputs.workflows == 'true'

      # - name: Test configuration
      #   run: ansible-playbook playbooks/build_all.yml -i inventory.yml --tags generate

      - name: Build DC01
        run: ansible-playbook playbooks/build_dc01.yml -i inventory.yml --tags generate
        if: steps.filter-site1.outputs.workflows == 'true'

      - name: Build DC01
        run: ansible-playbook playbooks/build_dc02.yml -i inventory.yml --tags generate
        if: steps.filter-site2.outputs.workflows == 'true'
