name: Deploy updates

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy-prod:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install Python requirements
        run: pip3 install "pyavd[ansible]==4.10.0"

      - name: Run pre-commit on files
        uses: pre-commit/action@v3.0.0

      - name: Check paths for Endpoints file
        uses: dorny/paths-filter@v3
        id: endpoints_xlsx
        with:
          filters: |
            workflows:
              - 'OtiNetworkConnectivitySpreadsheet.xlsx'

      - name: Check paths for group_vars/DC01
        uses: dorny/paths-filter@v3
        id: filter-site1
        with:
          filters: |
            workflows:
              - 'group_vars/DC01*'
              - 'group_vars/OTI*'

      - name: Check paths for group_vars/DC02
        uses: dorny/paths-filter@v3
        id: filter-site2
        with:
          filters: |
            workflows:
              - 'group_vars/DC02*'
              - 'group_vars/OTI*'

      - name: Install collections
        run: ansible-galaxy collection install -r requirements.yml
        if: steps.endpoints_xlsx.outputs.workflows == 'true' || steps.filter-site1.outputs.workflows == 'true' || steps.filter-site2.outputs.workflows == 'true'

      # - name: Build and deploy
      #   run: ansible-playbook playbooks/build_all.yml -i inventory.yml --tags deploy

      - name: deploy
        run: ansible-playbook playbooks/auto_deploy.yml -i inventory.yml
        if: steps.endpoints_xlsx.outputs.workflows == 'true' || steps.filter-site1.outputs.workflows == 'true' || steps.filter-site2.outputs.workflows == 'true'

      - name: validate
        run: ansible-playbook playbooks/validate_all.yml -i inventory.yml
        if: steps.endpoints_xlsx.outputs.workflows == 'true' || steps.filter-site1.outputs.workflows == 'true' || steps.filter-site2.outputs.workflows == 'true'

      - name: Commit report
        run: |
          git config --global user.name 'Joe Recchia'
          git config --global user.email 'joerecchia@users.noreply.github.com'
          git add .
          git commit -am "Automated validation report"
          git push
        if: steps.endpoints_xlsx.outputs.workflows == 'true' || steps.filter-site1.outputs.workflows == 'true' || steps.filter-site2.outputs.workflows == 'true'
